# Generated by Django 4.2.2 on 2023-06-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
