# Generated by Django 4.2.2 on 2023-06-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_finch_img_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='cat',
            new_name='finch',
        ),
    ]
